from datetime import datetime

def create_report(prediction, confidence, file_in=None):
    """Create a text-based report instead of PDF to avoid reportlab compatibility issues"""
    report_filename = f"CrySense_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    
    with open(report_filename, 'w') as f:
        f.write("=" * 60 + "\n")
        f.write("CrySense AI - Baby Cry Analysis Report\n")
        f.write("=" * 60 + "\n\n")
        
        f.write(f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        if file_in:
            f.write(f"Audio File: {file_in}\n\n")
        
        f.write(f"Predicted Cry Type: {prediction.upper()}\n")
        f.write(f"Confidence Level: {confidence*100:.2f}%\n\n")
        
        # Add urgency level
        urgency = "HIGH" if confidence >= 0.80 else ("MEDIUM" if confidence >= 0.60 else "LOW")
        f.write(f"Urgency: {urgency}\n\n")
        
        # Add recommendations
        recommendations = {
            "hungry": "🍼 Offer feeding. Watch for rooting/sucking cues.",
            "pain": "⚠️ Check for fever, rash, swelling. Consult pediatrician if persistent.",
            "sleepy": "😴 Dim lights, swaddle, reduce stimulation.",
            "discomfort": "👕 Check diaper, clothing, room temperature.",
            "diaper": "👶 Change diaper and ensure comfort."
        }
        
        rec = recommendations.get(prediction, "No specific recommendation.")
        f.write("Recommendation:\n")
        f.write(f"{rec}\n\n")
        
        f.write("=" * 60 + "\n")
        f.write("This report is auto-generated by the CrySense AI system.\n")
        f.write("⚠️ Research prototype • Not a substitute for professional medical advice\n")
        f.write("=" * 60 + "\n")
    
    return report_filename
